### PR TITLE
Simplify creating HTTP errors

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Contrary to its documentation, the `http-errors` module doesn't create a new error if it is already an HTTP error, so we don't need to check its type locally.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I'd like to try to write a characterization test given it's an undocumented behavior if this is not urgent - more for my learning than for likelihood of future breakages which is minimal.

**Comment by thewilkybarkid** [comment]
More meant that it doesn't replicate the same error, rather than being something that unexpected.

**Review by nlisgo — APPROVED** [review]
@thewilkybarkid is there a related open issue on the `http-errors` project. At least to address the documentation?

**Comment by thewilkybarkid** [comment]
Commented at https://github.com/jshttp/http-errors/pull/37#issuecomment-576664583.

**Pull request merged**
