### PR TITLE
Added type for unknown error, based on input of http-errors library

### PR DESCRIPTION
**Pull request by stephenwf**
This gives the `unknown` type a concrete type before being passed to the create error.

The type for UnknownError is computed as:
```typescript
type UnknownError = Error | string | number | { [key: string]: any };
```
From `createHttpError.CreateHttpError` types package. As this is not exported, there is a quick `infer` type that will grab this value, even if it changes.

```typescript
// `T extends ( ...` indicates that there is a ternary
type UnknownError<T = CreateHttpError> = T extends (
    // This expression is a generic shape of an input (in this case `CreateHttpError`)
    //  The `infer` keyword determines the true-ness of the statement
    (event: infer ErrorShape, ...args: unknown[]) => HttpError
  // When true, the value of the type is `ErrorShape` (a generic value, inferred above)
  // When false, the value is never and will error (same as the return type when throwing an exception)
  ) ? ErrorShape : never;
```

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
> As this is not exported

Sounds like it could be added upstream?

**Comment by thewilkybarkid** [comment]
Opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40487.

**Comment by stephenwf** [comment]
If we add the following to jest.config.js
```
globals: {
    'ts-jest': {
      tsConfig: {
        strict: false,
      },
    },
  },
```

that will disable strict mode just for tests (which should streamline creating tests).

**Comment by thewilkybarkid** [comment]
Type change has been merged and released.

**Review by thewilkybarkid — APPROVED** [review]
(Assuming you're happy with the changes!)

**Comment by stephenwf** [comment]
~Changed looks good, didn't spot the `UnknownError` type~ Re-read! :shipit:

**Pull request merged**
