### PR TITLE
Remove Travis CI build

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/libero/publisher/issues/340

Follow up to https://github.com/libero/article-store/pull/74/

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Removing the `Travis CI - Pull Request` required check from https://github.com/libero/article-store/settings/branch_protection_rules/11906254 /cc @libero/node-js-reviewers

**Comment by giorgiosironi** [comment]
See no equivalent to a global commit status to check for the `CI` workflow, besides a spurious `.github/workflows/ci.yml` which I don't think is still being produced.

**Comment by giorgiosironi** [comment]
> See no equivalent to a global commit status to check for the CI workflow

AFAIK this cannot be created manually, because the [`GITHUB_TOKEN` provided to fork builds is read only](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token).

**Comment by giorgiosironi** [comment]
Can check all of them if we want, but the list needs to be maintained in case they are renamed, added or removed.

**Review by thewilkybarkid — APPROVED** [review]

**Pull request merged**
